### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by bonelifer** [bluezed/repository.bluezed#1] opened 2016-10-29 22:11 UTC
It will either tell me I've entered the username/pass incorrectly or it tells me my token has expired.

http://pastebin.com/8PzsD6Cm

**Comment by bonelifer** [comment] 2016-10-29 22:20
Apparently already reported in the topic on Kodi.tv: http://forum.kodi.tv/showthread.php?tid=287868&pid=2399908#pid2399908

**Comment by bluezed** [comment] 2016-10-30 06:28
Sorry but I can't reproduce the issue here and the log does not really give me anything to go by. Could you maybe create a debug-log as well?

The forum entry you refer to was fixed on the same day so that shouldn't be an issue any longer. Also no one else has reported this so far so I have to suspect this is something to do  with your particular setup.

**Comment by bonelifer** [comment] 2016-10-30 09:26
Actually after hitting save and re-entering settings, it worked. How would I create a debug-log?

**Comment by bluezed** [comment] 2016-10-31 11:20
Creating a debug log is explained here: http://kodi.wiki/view/Log_file/Easy

Closing for now...

**Closed as completed by bluezed** 2016-10-31 11:20 UTC
